# Generated by Django 4.2.1 on 2023-05-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.IntegerField(primary_key=True, serialize=False)),
                ('airline', models.CharField(max_length=100)),
                ('passengers', models.IntegerField(default=0)),
                ('available_seats_economy', models.IntegerField()),
                ('available_seats_business', models.IntegerField()),
                ('available_seats_first', models.IntegerField()),
                ('flight_duration', models.TimeField()),
                ('dateOfDeparture', models.DateField()),
                ('eta', models.TimeField()),
                ('etd', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('airport_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('plane_id', models.IntegerField(primary_key=True, serialize=False)),
                ('num_economy_seats', models.IntegerField()),
                ('num_business_seats', models.IntegerField()),
                ('num_first_class_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.IntegerField(primary_key=True, serialize=False)),
                ('economy_price', models.FloatField()),
                ('business_price', models.FloatField()),
                ('first_class_price', models.FloatField()),
                ('currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('num_seats_economy', models.IntegerField()),
                ('num_seats_business', models.IntegerField()),
                ('num_seats_first', models.IntegerField()),
                ('confirmed_status', models.BooleanField()),
                ('time_started', models.DateTimeField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirlineAPI.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirlineAPI.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='AirlineAPI.location'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='AirlineAPI.location'),
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirlineAPI.plane'),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirlineAPI.price'),
        ),
    ]
